import { Job } from "../components/home/JobCard";

export const DUMMY_JOBS: Job[] = [
    {
        id: '1',
        title: 'Fashion Model',
        company: 'Nike Middle East',
        logoInitial: 'N',
        logoColor: '#4B5563',
        rating: 4.8,
        matchScore: 98,
        isVerified: true,
        tag: 'Urgent',
        location: 'Dubai Mall, Dubai',
        date: 'Dec 18-20, 2024',
        price: 'AED 2,500',
        priceUnit: '/day',
        reviews: 0
    },
    {
        id: '2',
        title: 'Event Host',
        company: 'Atlantis The Royal',
        logoInitial: 'A',
        logoColor: '#4B5563',
        rating: 5.0,
        reviews: 156,
        matchScore: 92,
        isVerified: true,
        tag: 'Premium',
        location: 'Palm Jumeirah, Dubai',
        date: 'Dec 31, 2024',
        price: 'AED 3,200',
        priceUnit: '/event',
    },
    {
        id: '3',
        title: 'Commercial Actor',
        company: 'Emirates Airlines',
        logoInitial: 'E',
        logoColor: '#DC2626',
        rating: 4.9,
        reviews: 89,
        matchScore: 88,
        isVerified: true,
        location: 'Dubai Media City',
        date: 'Jan 15-16, 2025',
        price: 'AED 5,000',
        priceUnit: '/shoot',
    },
];